### ISSUE TITLE
请问密钥如何获取

### ISSUE THREAD

**Issue by linlinago** [0honus0/CaoLiu_AutoReply#11]
如题

**Comment by 0honus0** [comment]
草榴网站添加两步验证的时候会有

**Comment by linlinago** [comment]
> 草榴网站添加两步验证的时候会有

不开启两步验证无法使用脚本吗

**Comment by 0honus0** [comment]
可以，但有一部分帖子不开没法回复

**Comment by linlinago** [comment]
> 可以，但有一部分帖子不开没法回复

明白了，那我不开启的话密钥这一栏是留空还是注释掉

**Comment by 0honus0** [comment]
随便写

**Comment by linlinago** [comment]
> 随便写

我之前执行过一次，貌似没有成功，我看日志里写的是
我的ID sleep 1980
我的ID：None
我的ID is invalid

**Comment by linlinago** [comment]
> 

我应该是忘记修改域名了

**Comment by 0honus0** [comment]
详细原因没法确认，调试可以账号密码发我邮箱，honusmr@gmail.com

**Comment by pooneyy** [comment]
> > 可以，但有一部分帖子不开没法回复
> 
> 明白了，那我不开启的话密钥这一栏是留空还是注释掉

不开启2FA时密钥这一栏应该留空，如果注释掉会报`KeyError`错误；
默认的`t66y.com`在境内不使用代理是访问不了的
