### ISSUE TITLE
是否考虑增加自动更新功能？

### ISSUE THREAD

**Issue by pooneyy** [0honus0/CaoLiu_AutoReply#12]
检测到版本变动后，从`https://fastly.jsdelivr.net/gh/0honus0/CaoLiu_AutoReply@master/AutoReply.py`请求最新版代码
可从配置文件：
```yaml
gobal_config:
    AutoUpdate: True
```
设置自动更新，如果为False，在日志打印更新提醒。

**Comment by 0honus0** [comment]
可以添加
