### ISSUE TITLE
大佬解决下重复回帖问题

### ISSUE THREAD

**Issue by lby251** [0honus0/CaoLiu_AutoReply#14]
我是挂在青龙下面用的，没有1024限制的号总是一个帖子重复回贴。

**Comment by 0honus0** [comment]
连续的在一个帖子下回复吗？

**Comment by 0honus0** [comment]
日志文件可以提供下吗

**Comment by lby251** [comment]
> 连续的在一个帖子下回复吗？

恩，在一个帖子下隔着一个人的回复又回了，在青龙里面日志没回帖的，能加个帖子验证，一个帖子回一次就完美了

**Comment by 0honus0** [comment]
现在就是一个帖子只能回复一次。我这边会在目录下生成一个日志文件，你可以找下运行目录下的文件

**Comment by lby251** [comment]
> 现在就是一个帖子只能回复一次。我这边会在目录下生成一个日志文件，你可以找下运行目录下的文件

好的  我先跑小号试试了  谢谢大佬
