### ISSUE TITLE
python AutoReply.py 执行后报错

### ISSUE THREAD

**Issue by linsan2681** [0honus0/CaoLiu_AutoReply#17]
大佬，执行脚本提示 

`File "AutoReply.py", line 16`
`    log = logging.getLogger(f"{projectName}")`
`                                           ^`
`SyntaxError: invalid syntax`

python 版本是 Python 2.7.16

**Comment by 0honus0** [comment]
需要python3

**Comment by linsan2681** [comment]
> 需要python3
执行python3 AutoReply.py 是啵？
`Traceback (most recent call last):`
`  File "AutoReply.py", line 6, in <module>`
`    import json, yaml`
`  File "/root/CaoLiu_AutoReply-master/yaml/__init__.py", line 2, in <module>`
`    from error import *`
`ModuleNotFoundError: No module named 'error'`
QAQ
Python 3.7.3

**Comment by 0honus0** [comment]
是的

**Comment by 0honus0** [comment]
你的 python3 环境估计有点奇怪，依赖路径找不到

**Comment by pooneyy** [comment]
你安装的PyYAML可能是python2的？试试这个
```
pip3 install -r requirements.txt -t ./
```
安装之前记得把`CaoLiu_AutoReply-master`文件夹里的全部依赖删干净。
