### ISSUE TITLE
讨论：怎样避免被禁言？最近好几个号因为灌水被封了。

### ISSUE THREAD

**Issue by pooneyy** [0honus0/CaoLiu_AutoReply#20]
每天也只发十条评论

**Comment by 0honus0** [comment]
单ip挂太多账号了？我这边没遇到过

**Comment by pooneyy** [comment]
> 单ip挂太多账号了？我这边没遇到过

4个被封了2个

**Comment by 0honus0** [comment]
看一下被封的回复了哪些帖子，是不是有一些明确不让回复什么了，或者重复回复了

**Comment by pooneyy** [comment]
> 重复回复

没有明确不让回复的，但是有一个重复回复的。中午打开的时候回复了一次，后来机器故障了，晚上的时候打开，某条帖子又回了一次

**Comment by pooneyy** [comment]
如果是重复回复的原因的话，能否从 `personal.php?action=post` 获取历史回复的帖子，运行的时候把它们加到屏蔽列表里？

但是这个功能的话我就没能力添加了，最近在忙考试。

**Comment by 0honus0** [comment]
也可以把每次运行回复的写到文件里面，每次运行读取一下

**Comment by Niceboatang** [comment]
不需要加载字典？
为什么我设置好后，提示 

[2023-06-22 18:09:24,183] [INFO]        yang4000 : None
[2023-06-22 18:09:39,281] [INFO]        w1025 : None
[2023-06-22 18:09:54,377] [INFO]        wy345 : None
[2023-06-22 18:09:54,377] [INFO]        --------------------->>>


这样是不是没运行成功

**Comment by Niceboatang** [comment]
获取威望失败 ，是为什么？

**Comment by 0honus0** [comment]
换个分区回复就好
