### ISSUE TITLE
官方登录增加cktime选择，继续默认为0无法登录成功

### ISSUE THREAD

**Issue by hoopec** [0honus0/CaoLiu_AutoReply#23]
cktime需要选择ck有效期，手动登录默认为31536000秒（1年），继续像代码中为0无法登录成功
另：希望将150行和308行的fid提取为config参数，方便进行回复板块的切换
建议增加未开启两步验证的Cler判断
![image](https://github.com/0honus0/CaoLiu_AutoReply/assets/62711787/429c582f-1f90-4557-a735-fcf776296a00)

**Comment by 0honus0** [comment]
已更新

**Comment by hoopec** [comment]
抱歉，cktime好像我不太确定，麻烦你这边再测试一下，我是遇到了获取个人信息失败，返回为None，以为是login的问题
![image](https://github.com/0honus0/CaoLiu_AutoReply/assets/62711787/f16de68e-2dec-48d6-81bc-c91e6070ae8b)

**Comment by hoopec** [comment]
而且login success/failed都没有显示。可能是我的账号问题吧。。。

**Comment by 0honus0** [comment]
我重新看了下请求，参数变了
也可能是不是一个登陆界面的原因，有两个入口好像。
你这个更像网络问题

hoopec ***@***.***>于2023年7月1日 周六01:23写道：
