### ISSUE TITLE
关于输出到终端的日志的等级的问题

### ISSUE THREAD

**Issue by pooneyy** [0honus0/CaoLiu_AutoReply#3]
https://github.com/0honus0/CaoLiu_AutoReply/blob/5e4367768d7096455ee32f301fd46ce1eda8c76f/AutoReply.py#L17

写入文件的日志需要精简，第26行设置为只输出`INFO`级日志
但是第17行将原先的“`level=logging.DEBUG`”改为“`level=logging.INFO`”后，终端将不会显示DEBUG级别的日志。所以建议改回原先的 `log.setLevel(level=logging.DEBUG)` 。

**Comment by 0honus0** [comment]
可以
