### ISSUE TITLE
requests.exceptions.ProxyError 报错

### ISSUE THREAD

**Issue by tomasasho** [0honus0/CaoLiu_AutoReply#9]
猜测问题产生是账号数量多于10个时报错

requests.exceptions.ProxyError: HTTPSConnectionPool(host='t66y.com', port=443): Max retries exceeded with url: /index.php (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

偶尔运行着脚本就报此错误

**Comment by 0honus0** [comment]
每次都会吗，还是偶尔

**Comment by tomasasho** [comment]
还是比较频繁的.包括第一版代码1024-AutoReply这个报错也经常出现

回溯路径:
1.http.client.RemoteDisconnected: Remote end closed connection without response
2.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='t66y.com', port=443): Max retries exceeded with url: /thread0806.php?fid=7&search=today (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))   
3.requests.exceptions.ProxyError: HTTPSConnectionPool(host='t66y.com', port=443): Max retries exceeded with url: /thread0806.php?fid=7&search=today (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))    

查相关的一些资料:
- [使用python requests报错requests.exceptions.SSLError: HTTPSConnectionPool](https://www.xmxblog.com/?p=373)
- [求助：python接口脚本，使用requests中的代理，结果报错](https://ceshiren.com/t/topic/9972)
- [Max retries exceeded with url--问题解决方案 - ClareBaby01 - 博客园](https://www.cnblogs.com/renjie1105/p/15162614.html)
- [解决Python3 urllib3 urllib3.exceptions.maxretryerror: httpsconnectionpool(host=‘xxxxx‘, port=443)\_urllib3.exceptions.maxretryerror: sockshttpsconnec\_南木不休的博客-CSDN博客](https://blog.csdn.net/weixin_38791562/article/details/123510191)


**So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase **
多个请求到同一个host, 复用底层TCP

**Comment by 0honus0** [comment]
正常来说是一个个请求的，不会出现同时大量请求的。
可能是网络稳定性的问题，后面可以考虑增加重试机制尽量避免错误

**Comment by 0honus0** [comment]
已更新，可以尝试更新之后测试下
